name: First workflow
on:
    push:
        branches:
        - main
jobs:
    first-job:
        uses: ./.github/workflows/second.yml
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_ID_MAPPING_TABLE: ${{ secrets.SLACK_ID_MAPPING_TABLE }}
        with: 
            LAST_COMMIT_MESSAGE: ${{ github.event.head_commit.message }}
            LAST_COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
            LAST_COMMIT_TIMESTAMP: ${{ github.event.head_commit.timestamp }}
            REPOSITORY_NAME: ${{ github.repository }}
            BRANCH_NAME: ${{ github.ref }}
            GITHUB_RUN_ID: ${{ github.run_id }}
            GITHUB_RUN_NUMBER: ${{ github.run_number }}
            MESSAGE_COLOR: "#000000"
            DEPLOYMENT_STATUS: "실패"
            FAIL_REASON: "그냥 실패야 임마"
