name: First workflow
on:
    push:
        branches:
        - main
jobs:
    first-job:
        uses: ./.github/workflows/second.yml
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_ID_MAPPING_TABLE: ${{ secrets.SLACK_ID_MAPPING_TABLE }}
        with: 
            LAST_COMMIT_MESSAGE: ${{ github.action }}
            LAST_COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
            LAST_COMMIT_TIMESTAMP: ${{github.event.repository.updated_at}}
            REPOSITORY_NAME: ${{ github.repository }}
            BRANCH_NAME: "qa-develop"
            GITHUB_RUN_ID: ${{ github.run_id }}
            GITHUB_RUN_NUMBER: ${{ github.run_number }}
            MESSAGE_COLOR: "#FFFFFF"
            DEPLOYMENT_STATUS: "성공"
            FAIL_REASON: "그냥 성공이야 임마"
