name: First workflow
on:
    push:
        branches:
        - main
jobs:
    first-job:
        uses: ./.github/workflows/second.yml
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_ID_MAPPING_TABLE: ${{ secrets.SLACK_ID_MAPPING_TABLE_FOR_QA }}
        with: 
            WORKFLOW_NAME: ${{ github.workflow }}
            LAST_COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
            LAST_COMMIT_MESSAGE: ${{github.event.head_commit.message}}
            WORKFLOW_START_TIME: ${{github.event.repository.pushed_at}}
            REPOSITORY_NAME: ${{ github.repository }}
            BRANCH_NAME: ${{ github.ref_name }}
            GITHUB_RUN_ID: ${{ github.run_id }}
            GITHUB_RUN_NUMBER: ${{ github.run_number }}
            MESSAGE_COLOR: "#FFFFFF"
            DEPLOYMENT_STATUS: "Succeeded"
            FAIL_REASON: "N/A"
    third-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "this is third-job"
                exit 1
    fourth-job:
        needs: third-job
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "this is fourth-job"
    catch-error:
        needs: [first-job,third-job,fourth-job]
        if: ${{ failure() }}
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "catch error"


