name: First workflow
on:
    push:
        branches:
        - main
jobs:
    first-job:
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "this is first-job"
    second-job:
        needs: first-job
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "this is third-job"
                exit 1
        outputs:
            failure-reasons: "Because of ${{github.jobs[github.job]}}"
    third-job:
        needs: second-job
        runs-on: ubuntu-latest
        steps:
            - run: |
                echo "this is fourth-job"

    success-slack-message:
        needs: [first-job,second-job,third-job]
        uses: ./.github/workflows/second.yml
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_ID_MAPPING_TABLE: ${{ secrets.SLACK_ID_MAPPING_TABLE_FOR_QA }}
        with: 
            BRANCH_NAME: ${{ github.ref_name }}
            GITHUB_RUN_ID: ${{ github.run_id }}
            GITHUB_RUN_NUMBER: ${{ github.run_number }}
            LAST_COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
            LAST_COMMIT_ID: ${{github.event.head_commit.id}}
            LAST_COMMIT_MESSAGE: ${{github.event.head_commit.message}}
            REPOSITORY_NAME: ${{ github.repository }}
            WORKFLOW_START_TIME: ${{github.event.repository.pushed_at}}
            WORKFLOW_NAME: ${{ github.workflow }}
            DEPLOYMENT_STATUS: "Succeeded"
            FAIL_REASONS: ""
            MESSAGE_COLOR: "#28A745"

    failure-slack-message:
        needs: [first-job,second-job,third-job]
        if: ${{ failure() }}
        
        uses: ./.github/workflows/second.yml
        secrets:
            SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
            SLACK_ID_MAPPING_TABLE: ${{ secrets.SLACK_ID_MAPPING_TABLE_FOR_QA }}
        with: 
            BRANCH_NAME: ${{ github.ref_name }}
            GITHUB_RUN_ID: ${{ github.run_id }}
            GITHUB_RUN_NUMBER: ${{ github.run_number }}
            LAST_COMMIT_AUTHOR: ${{ github.event.head_commit.author.name }}
            LAST_COMMIT_ID: ${{github.event.head_commit.id}}
            LAST_COMMIT_MESSAGE: ${{github.event.head_commit.message}}
            REPOSITORY_NAME: ${{ github.repository }}
            WORKFLOW_START_TIME: ${{github.event.repository.pushed_at}}
            WORKFLOW_NAME: ${{ github.workflow }}
            DEPLOYMENT_STATUS: "Failed"
            FAIL_REASONS: ${{needs.second-job.outputs.failure-reasons}}
            MESSAGE_COLOR: "#CB2431"


