name: Second Workflow
on:
    workflow_call:
        secrets:
            SLACK_WEBHOOK_URL:
                required: true
            SLACK_ID_MAPPING_TABLE:
                required: true
        inputs:
            WORKFLOW_NAME:
                required: true
                type: string
            LAST_COMMIT_AUTHOR:
                required: true
                type: string
            WORKFLOW_START_TIME:
                required: true
                type: string
            REPOSITORY_NAME:
                required: true
                type: string
            BRANCH_NAME:
                required: true
                type: string
            GITHUB_RUN_ID:
                required: true
                type: string
            GITHUB_RUN_NUMBER:
                required: true
                type: string
            MESSAGE_COLOR:
                required: true
                type: string
            DEPLOYMENT_STATUS:
                type: string
            FAIL_REASON:
                required: true
                type: string

jobs:
    second-job:
        runs-on: ubuntu-latest
        steps:
            - name: Make payload
              run: |
                workflowName="${{ inputs.WORKFLOW_NAME }}"
                readableWorkflowStartTime=$(TZ='Asia/Seoul' date -d @${{ inputs.WORKFLOW_START_TIME }} '+%Y-%m-%d %H:%M:%S')
                lastCommitAuthor="${{ inputs.LAST_COMMIT_AUTHOR }}"
                repositoryName="${{ inputs.REPOSITORY_NAME }}"
                branchName="${{ inputs.BRANCH_NAME }}"
                githubRunId="${{ inputs.GITHUB_RUN_ID }}"
                githubRunNumber="${{ inputs.GITHUB_RUN_NUMBER }}"
                messageColor="${{ inputs.MESSAGE_COLOR }}"
                deploymentStatus="${{ inputs.DEPLOYMENT_STATUS }}"
                failReason="${{ inputs.FAIL_REASON }}"
                authorSlackId=$(echo '${{ secrets.SLACK_ID_MAPPING_TABLE }}' | jq -r .${{ inputs.LAST_COMMIT_AUTHOR }})
                jsonPayload=$(jq -n \
                --arg workflowName "$workflowName" \
                --arg lastCommitAuthor "$lastCommitAuthor" \
                --arg workflowStartTime "$readableWorkflowStartTime" \
                --arg repositoryName "$repositoryName" \
                --arg branchName "$branchName" \
                --arg githubRunId "$githubRunId" \
                --arg githubRunNumber "$githubRunNumber" \
                --arg messageColor "$messageColor" \
                --arg deploymentStatus "$deploymentStatus" \
                --arg failReason "$failReason" \
                --arg authorSlackId "$authorSlackId" \
                '{
                    "blocks": [
                    {
                        "type": "section",
                        "text": {
                        "type": "mrkdwn",
                        "text": ("Github Actions: <https://github.com/" + $repositoryName + "/actions/runs/" + $githubRunId + "|" + $workflowName + " #" + $githubRunNumber + "> "+ $deploymentStatus + " on " + $branchName)
                        }
                    }
                    ],
                    "attachments": [
                    {
                        "color": $messageColor,
                        "blocks": [
                        {
                            "type": "header",
                            "text": {
                            "type": "plain_text",
                            "text": $deploymentStatus
                            }
                        },
                        {
                            "type": "section",
                            "fields": [
                            {
                                "type": "mrkdwn",
                                "text": ("*Run Number:*\n" + "<https://github.com/" + $repositoryName + "/actions/runs/" + $githubRunId + "|" + $workflowName + " #" + $githubRunNumber + ">"),
                            },
                            {
                                "type": "mrkdwn",
                                "text": ("*Reasons:*\n" + $failReason)
                            },
                            {
                                "type": "mrkdwn",
                                "text": ("*Pusher:*\n<@" + $authorSlackId + ">")
                            },
                            {
                                "type": "mrkdwn",
                                "text": ("*Repository:*\n" + $repositoryName + " |\n" + $workflowStartTime)
                            }
                            ]
                        }
                        ]
                    }
                    ]
                }')
                curl -X POST -H 'Content-type: application/json' --data "$jsonPayload" ${{ secrets.SLACK_WEBHOOK_URL }}


