name: Second Workflow
on:
    workflow_call:
        secrets:
            SLACK_WEBHOOK_URL:
                required: true
            SLACK_ID_MAPPING_TABLE:
                required: true
        inputs:
            BRANCH_NAME:
                required: true
                type: string
            GITHUB_RUN_ID:
                required: true
                type: string
            GITHUB_RUN_NUMBER:
                required: true
                type: string
            LAST_COMMIT_AUTHOR:
                required: true
                type: string
            LAST_COMMIT_ID:
                required: true
                type: string
            LAST_COMMIT_MESSAGE:
                required: true
                type: string
            REPOSITORY_NAME:
                required: true
                type: string
            WORKFLOW_NAME:
                required: true
                type: string
            WORKFLOW_START_TIME:
                required: true
                type: string
            DEPLOYMENT_STATUS:
                type: string
                default: "Failed"
            FAIL_REASONS:
                type: string
                default: ""
            MESSAGE_COLOR:
                type: string
                default: "#CB2431"
jobs:
    send-messages-to-slack:
        runs-on: ubuntu-latest
        steps:
            - run: |    
                echo "${{inputs.FAIL_REASONS}}" 
                branchName="${{ inputs.BRANCH_NAME }}"
                githubRunId="${{ inputs.GITHUB_RUN_ID }}"
                githubRunNumber="${{ inputs.GITHUB_RUN_NUMBER }}"
                lastCommitAuthor="${{ inputs.LAST_COMMIT_AUTHOR }}"
                lastCommitId="${{ inputs.LAST_COMMIT_ID }}"

                # Escape processing
                lastCommitMessage=$(jq -n --arg lcm "${{ inputs.LAST_COMMIT_MESSAGE }}" '($lcm)')
                lastCommitMessage="${lastCommitMessage:1:-1}"  

                repositoryName="${{ inputs.REPOSITORY_NAME }}"
                workflowName="${{ inputs.WORKFLOW_NAME }}"
                readableWorkflowStartTime=$(TZ='Asia/Seoul' date -d @${{ inputs.WORKFLOW_START_TIME }} '+%Y-%m-%d %H:%M:%S')
                deploymentStatus="${{ inputs.DEPLOYMENT_STATUS }}"
                failReasons="${{ inputs.FAIL_REASONS }}"
                messageColor="${{ inputs.MESSAGE_COLOR }}"
                authorSlackId=$(echo '${{ secrets.SLACK_ID_MAPPING_TABLE }}' | jq -r --arg key "$lastCommitAuthor" '.[$key] // $key')

                jsonPayload=$(jq -n \
                --arg branchName "$branchName" \
                --arg githubRunId "$githubRunId" \
                --arg githubRunNumber "$githubRunNumber" \
                --arg lastCommitMessageLink "<https://github.com/$repositoryName/commit/$lastCommitId|$lastCommitMessage>" \
                --arg repositoryName "$repositoryName" \
                --arg workflowNameLink "<https://github.com/$repositoryName/actions/runs/$githubRunId|$workflowName #$githubRunNumber>" \
                --arg workflowStartTime "$readableWorkflowStartTime" \
                --arg deploymentStatus "$deploymentStatus" \
                --arg failReasons "$failReasons" \
                --arg messageColor "$messageColor" \
                --arg authorSlackId "$authorSlackId" \
                '{
                    "blocks": [
                    {
                        "type": "section",
                        "text": {
                        "type": "mrkdwn",
                        "text": ("Github Actions: " + $workflowNameLink + " " + $deploymentStatus + " on " + $branchName)
                        }
                    }
                    ],
                    "attachments": [
                    {
                        "color": $messageColor,
                        "blocks": [
                        {
                            "type": "header",
                            "text": {
                            "type": "plain_text",
                            "text": $deploymentStatus
                            }
                        },
                        {
                            "type": "section",
                            "fields": [
                            {
                                "type": "mrkdwn",
                                "text": ("*Workflow:*\n" + $workflowNameLink + "\n" + $failReasons),
                            },
                            {
                                "type": "mrkdwn",
                                "text": ("*Last commit message:*\n" + $lastCommitMessageLink)
                            },
                            {
                                "type": "mrkdwn",
                                "text": ("*Assignee:*\n<" + $authorSlackId + ">")
                            },
                            {
                                "type": "mrkdwn",
                                "text": ("*Start time of workflow:*\n" + $workflowStartTime)
                            }
                            ]
                        }
                        ]
                    }
                    ]
                }')
                curl -X POST -H 'Content-type: application/json' --data "$jsonPayload" ${{ secrets.SLACK_WEBHOOK_URL }}


